trigger: none

parameters:
- name: destroyInfrastructure
  displayName: 'Destroy Infrastructure?'
  type: boolean
  default: false

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-variables

stages:
- stage: 'Validate'
  displayName: 'Validate'
  jobs:
  - job: 'Validate'
    displayName: 'Validate Terraform'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
        TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
        TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
        TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)

    - script: |
        terraform fmt
      displayName: 'Terraform Format'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

    - script: |
        terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

- stage: 'Plan'
  displayName: 'Plan'
  dependsOn: 'Validate'
  condition: eq('${{ parameters.destroyInfrastructure }}', 'false')
  jobs:
  - job: 'Plan'
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
        TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
        TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
        TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)

    - script: |
        terraform plan
      displayName: 'Terraform Plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
        TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
        TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
        TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)

- stage: 'Apply'
  displayName: 'Apply'
  dependsOn: 'Plan'
  condition: and(succeeded(), eq('${{ parameters.destroyInfrastructure }}', 'false'))
  jobs:
  - deployment: 'Apply'
    displayName: 'Terraform Apply'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: 'Terraform Init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
              TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
              TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
              TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)

          - script: |
              terraform apply -auto-approve
            displayName: 'Terraform Apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
              TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
              TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
              TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

- stage: 'Destroy'
  displayName: 'Destroy Infrastructure'
  condition: eq('${{ parameters.destroyInfrastructure }}', 'true')
  dependsOn: []
  jobs:
  - deployment: 'Destroy'
    displayName: 'Terraform Destroy'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: 'Terraform Init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
              TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
              TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
              TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)

          - script: |
              terraform destroy -auto-approve
            displayName: 'Terraform Destroy'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              TF_VAR_azure_subscription_id: $(AZURE_SUBSCRIPTION_ID)
              TF_VAR_azure_tenant_id: $(AZURE_TENANT_ID)
              TF_VAR_azure_client_id: $(AZURE_CLIENT_ID)
              TF_VAR_azure_client_secret: $(AZURE_CLIENT_SECRET)